### ISSUE TITLE
python3 and tutorial

### ISSUE THREAD

**Issue by calugo** [tdsmith/eleven#3]
Hi Tim,
this is an excellent effort, but it seems a bit abandoned, I have made some minor modificiations to some  functions to run in python3 (e.g replacing xranges for range) etc. Then started to put together a jupyter notebook to reproduce the results of the 2002 original paper (the way the R implementation does, I also do not like R). So I have prepared a dataframe with the raw data from the original paper, however I am getting results which are not close to those in the original paper or the R code. 

My question is regarding the method itself and the input of the Cq data. Does the raw  Cq  need to be transformed before applying the ranking  computations? 

See the R outcome below:

![genorm](https://user-images.githubusercontent.com/6739276/45152010-b9e1ee80-b1c7-11e8-98bd-9f2222ed2e1b.png)

![vgneorm](https://user-images.githubusercontent.com/6739276/45152098-fada0300-b1c7-11e8-9912-f9038b26f09e.png)

I have checked that the raw Cq's are the same in my dataframe  and the R dataset, so I guess I am not using the library correctly, so I was wondering  if you could give a me a hand here?

Sorry for the hassle!

Carlos

**Comment by tdsmith** [comment]
You're right that I'm no longer maintaining this software. The tests use some data from the Vandesompele paper, so they may serve as a reference.
